---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker ansible ansible-lint
script:
  - ansible-lint -x 401,405 .
