# Server swap tweaking

- name: Linux Server | Kernel | Configure swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Linux Server | Kernel | Configure grub cgroups/swap
  shell: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | grep -c "cgroup_enable=memory swapaccount=1"
  register: cgroup_status
  ignore_errors: true

- name: Linux Server | Kernel | Configure grub cgroups/swap
  lineinfile: dest="/etc/default/grub" regexp='GRUB_CMDLINE_LINUX_DEFAULT="(.*)"' line='GRUB_CMDLINE_LINUX_DEFAULT="\1 cgroup_enable=memory swapaccount=1"' backrefs=yes
  when: cgroup_status.stdout == "0"

- name: Linux Server | Kernel | Configure grub cgroups/swap
  shell: update-grub
  when: cgroup_status.stdout == "0"
